config/routes.rb
TickMaster::Application.routes.draw do
  resources :campaigns
  resources :tick_tracks
  
  root to: "tick_tracks#index"

  put "campaigns/:id/setCurrent" => "campaigns#setCurrent"
  put "/clearCurrent" => "campaigns#clearCurrent"

  put "tick_tracks/:id/incWound" => "tick_tracks#incWound"
  put "tick_tracks/:id/resetWound" => "tick_tracks#resetWound"

  put "tick_tracks/:id/incTick" => "tick_tracks#incTick"
  post "/decAll" => "tick_tracks#decAll"

end

app/models/campaign.rb
class Campaign < ActiveRecord::Base
  attr_accessible :GM, :active, :name
end

app/models/tick_track.rb
class TickTrack < ActiveRecord::Base
  attr_accessible :isPC, :name, :tick, :wound, :campaign_id, :bulkCount
  belongs_to :campaign
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  # GET /campaigns
  # GET /campaigns.json
  def index
    @campaigns = Campaign.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @campaigns }
    end
  end

  # GET /campaigns/1
  # GET /campaigns/1.json
  def show
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @campaign }
    end
  end

  # GET /campaigns/new
  # GET /campaigns/new.json
  def new
    @campaign = Campaign.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @campaign }
    end
  end

  # GET /campaigns/1/edit
  def edit
    @campaign = Campaign.find(params[:id])
  end

  # POST /campaigns
  # POST /campaigns.json
  def create
    @campaign = Campaign.new(params[:campaign])

    respond_to do |format|
      if @campaign.save
        format.html { redirect_to campaigns_url }
        format.json { render json: @campaign, status: :created, location: @campaign }
      else
        format.html { render action: "new" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /campaigns/1
  # PUT /campaigns/1.json
  def update
    @campaign = Campaign.find(params[:id])

    respond_to do |format|
      if @campaign.update_attributes(params[:campaign])
        format.html { redirect_to campaigns_url }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @campaign.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campaigns/1
  # DELETE /campaigns/1.json
  def destroy
    @campaign = Campaign.find(params[:id])
    @campaign.destroy

    respond_to do |format|
      format.html { redirect_to campaigns_url }
      format.json { head :no_content }
    end
  end

  #Set Current Campaign and Load /tick_tracks/
  def setCurrent
    @campaign = Campaign.find(params[:id])
    cookies.permanent[:campaign_id] = @campaign.id
    cookies.permanent[:campaign_name] = @campaign.name

    respond_to do |format|
      format.html { redirect_to tick_tracks_url }
      format.json { head :no_content }
    end
  end

  def clearCurrent
    cookies.delete :campaign_id
    cookies.delete :campaign_name

    respond_to do |format|
      format.html { redirect_to tick_tracks_url }
      format.json { head :no_content }
    end
  end

end

app/controllers/tick_tracks_controller.rb
class TickTracksController < ApplicationController
  # GET /tick_tracks
  # GET /tick_tracks.json
  def index
    @tick_tracks = TickTrack.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tick_tracks }
    end
  end

  # GET /tick_tracks/1
  # GET /tick_tracks/1.json
  def show
    @tick_track = TickTrack.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tick_track }
    end
  end

  # GET /tick_tracks/new
  # GET /tick_tracks/new.json
  def new
    @tick_track = TickTrack.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tick_track }
    end
  end

  # GET /tick_tracks/1/edit
  def edit
    @tick_track = TickTrack.find(params[:id])
  end

  # POST /tick_tracks
  # POST /tick_tracks.json
  def create
    @tick_track = TickTrack.new(params[:tick_track])
    if @tick_track.bulkCount != nil
      if @tick_track.bulkCount > 1
        labelAdd = 1
        @tick_track.name = @tick_track.name + " " + labelAdd.to_s
        saveSuccess = @tick_track.save
        until (labelAdd - 1) == @tick_track.bulkCount
          labelAdd += 1
          @tick_track = TickTrack.new(params[:tick_track])
          @tick_track.name = @tick_track.name + " " + labelAdd.to_s
          saveSuccess = @tick_track.save
        end
      else
        saveSuccess = @tick_track.save
      end
    else
      saveSuccess = @tick_track.save
    end

    respond_to do |format|
      if saveSuccess
        format.html { redirect_to tick_tracks_url }
        format.json { render json: @tick_track, status: :created, location: @tick_track }
      else
        format.html { render action: "new" }
        format.json { render json: @tick_track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tick_tracks/1
  # PUT /tick_tracks/1.json
  def update
    @tick_track = TickTrack.find(params[:id])

    respond_to do |format|
      if @tick_track.update_attributes(params[:tick_track])
        format.html { redirect_to tick_tracks_url }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tick_track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tick_tracks/1
  # DELETE /tick_tracks/1.json
  def destroy
    @tick_track = TickTrack.find(params[:id])
    @tick_track.destroy

    respond_to do |format|
      format.html { redirect_to tick_tracks_url }
      format.json { head :no_content }
    end
  end

  #PUT /tick_tracks/1/incTick?amount=X
  def incTick
    @tick_track = TickTrack.find(params[:id])
    if params[:amount] != nil
      @tick_track.tick += params[:amount].to_i
      @tick_track.save
    end

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  #POST /decAll
  def decAll
    @tick_tracks = TickTrack.all
    @tick_tracks.each do |tick_track|
      tick_track.decrement(:tick) if tick_track.tick > 0
      tick_track.tick = 0 if tick_track.tick < 0
      tick_track.save
    end
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  #PUT /tick_tracks/1/incWound?amount=X
  def incWound
    @tick_track = TickTrack.find(params[:id])
    if params[:amount] != nil
      @tick_track.wound += params[:amount].to_i
      @tick_track.save
    end

    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end

  #PUT /tick_tracks/1/resetWound
  def resetWound
    @tick_track = TickTrack.find(params[:id])
    @tick_track.wound = 0
    @tick_track.save
    
    respond_to do |format|
      format.html { redirect_to root_path }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/campaigns_helper.rb
module CampaignsHelper
end

app/helpers/tick_tracks_helper.rb
module TickTracksHelper
end

app/views/campaigns/_form.html.erb
<%= simple_form_for @campaign do |f| %>
<%= f.input :name, label: 'What is the name of the campaign?' %>
<%= f.input :GM, label: 'Who is the GM for this campaign?' %>
<%= f.input :active, label: 'Check this box to enable this campaign.' %>
<%= f.button :submit, "Done" , :class => "btn btn-primary" %>
<%= link_to 'Back', campaigns_path, :class => "btn" %>
<% end %>

app/views/campaigns/edit.html.erb
<h2>Editing Campaign</h2>

<%= render 'form' %>

app/views/campaigns/index.html.erb
<h2>All Campaigns</h2>

<table class= "table table-hover table-condensed">
  <tr style="border-top: 0;">
    <th>Name</th>
    <th>Gm</th>
    <th>Active</th>
    <th>Actions</th>
    <th>Select Campaign</th>
  </tr>

<% @campaigns.each do |campaign| %>
  <tr>
    <td style="vertical-align:middle"><t3><%= campaign.name %></t3> </td>
    <td style="vertical-align:middle"><%= campaign.GM %></td>
    <td style="vertical-align:middle"><%= campaign.active %></td>
    <td style="vertical-align:middle"><span class="btn-group"><%= link_to 'Edit', edit_campaign_path(campaign), :class => "btn btn-mini" %><%= link_to 'Delete', campaign, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-mini" %></span></td>
    <td style="vertical-align:middle"><%= link_to 'Select', "/campaigns/#{campaign.id}/setCurrent", :method => :put, :class => "btn btn-success" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Campaign', new_campaign_path, :class => "btn" %>
<%= link_to 'Deselect Campaign', "/clearCurrent/", :method => :put, :class => "btn" %>

app/views/campaigns/new.html.erb
<h2>New Campaign</h2>

<%= render 'form' %>

app/views/campaigns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @campaign.name %>
</p>

<p>
  <b>Gm:</b>
  <%= @campaign.GM %>
</p>

<p>
  <b>Active:</b>
  <%= @campaign.active %>
</p>


<%= link_to 'Edit', edit_campaign_path(@campaign) %> |
<%= link_to 'Back', campaigns_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TickMaster</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <link rel="apple-touch-icon" href="touch-icon-iphone.png" />
  <link rel="apple-touch-icon" sizes="72x72" href="touch-icon-ipad.png" />
  <link rel="apple-touch-icon" sizes="114x114" href="touch-icon-iphone-retina.png" />
  <link rel="apple-touch-icon" sizes="144x144" href="touch-icon-ipad-retina.png" />
  <link rel="shortcut icon" href="favicon.png" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
</head>
<body>
  <% cookie_name = cookies[:campaign_name] %>
    <div class="navbar navbar-static-top">
  <div class="navbar-inner">
    <div class="brand">TickMaster</div>
    <ul class="nav">
      <li class="divider-vertical"></li>
      <li><%= link_to (cookie_name != nil ? cookie_name : 'No Current Campaign'),"/tick_tracks/" %></li>
      <li class="divider-vertical"></li>
      <li><%= link_to 'Manage / Select Campaigns', "/campaigns/" %></li>
      <li class="divider-vertical"></li>
    </ul>
  </div>
</div>
<div class="container">

<%= yield %>
</div>
</body>
</html>

app/views/tick_tracks/_form.html.erb
<%= simple_form_for @tick_track do |f| %>
	<%= f.input :name, label: 'What is the name of the character?' %>
	<%= f.input :tick, label: 'What tick will they be starting on?', :value => 0, input_html: { class: 'input-small' } %>
	<%= f.input :isPC, label: 'Check this box if this is a player.' %>
	<% cookie_id = cookies[:campaign_id] %>

	<% if cookie_id != nil %>
		<%= f.input :campaign_id, collection: Campaign.where(:active => true), :selected => Integer(cookie_id), label: 'Select your campaign:' %>
	<% else %>
		<%= f.input :campaign_id, collection: Campaign.where(:active => true), label: 'Select your campaign:' %>
	<% end %>

	<% if @tick_track.new_record? %>
		<%= f.input :bulkCount, collection: 0..9, label: 'Extra copies of this character?', value: 0, input_html: { class: 'input-small' } %>
		<%= f.hidden_field :wound, value: 0 %>
	<% end %>

	<%= f.button :submit, "Done" , :class => "btn btn-primary" %>
	<% if !@tick_track.new_record? %>
		<%= link_to 'Delete', @tick_track, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %>
	<% end %>
	<%= link_to 'Back', root_path, :class => "btn" %>
<% end %>

app/views/tick_tracks/edit.html.erb
<h2>Edit Character</h2>

<%= render 'form' %>

app/views/tick_tracks/index.html.erb
<% cookie_id = cookies[:campaign_id] %>
<% if cookie_id != nil %>
<% @tick_tracks = @tick_tracks.select {|obj| obj.campaign_id == Integer(cookie_id)} %>
<h2>Player Characters</h2>

<div class="row well">
<% @PCtracks = @tick_tracks.select { |obj| (obj.isPC == true && obj.campaign.active == true) } %>
<% @PCtracks.sort!{ |a,b| a.name <=> b.name} %>
<% @PCtracks.each do |tick_track| %>
  <div class="span2 trackbox <%= tick_track.tick != nil ? (tick_track.tick >=10 ? "offbalance" : "tick" + tick_track.tick.to_s()) : "errortick" %> <%= tick_track.wound != nil ? (tick_track.wound == 0 ? "wound-none" : (tick_track.wound < 3 ? "wound-light" : (tick_track.wound < 9 ? "wound-major" : (tick_track.wound < 27 ? "wound-severe" : "wound-critical")))) : "errorwound" %>">
    <h4><%= link_to tick_track.name, edit_tick_track_path(tick_track) %><br></h4>
    <h1><%= tick_track.tick %><br></h1>
   <p><div class="btn-group">
      <%= link_to '1', "/tick_tracks/#{tick_track.id}/incTick?amount=1", :method => :put, :class => "btn btn-mini" %>
      <%= link_to '2', "/tick_tracks/#{tick_track.id}/incTick?amount=2", :method => :put, :class => "btn btn-mini" %>
      <%= link_to '3', "/tick_tracks/#{tick_track.id}/incTick?amount=3", :method => :put, :class => "btn btn-mini" %>
      <%= link_to '4', "/tick_tracks/#{tick_track.id}/incTick?amount=4", :method => :put, :class => "btn btn-mini" %>
      <%= link_to '5', "/tick_tracks/#{tick_track.id}/incTick?amount=5", :method => :put, :class => "btn btn-mini" %>
      <a class="btn dropdown-toggle btn-mini" data-toggle="dropdown" href="#"><i class="icon-fire icon-black"></i></a>
      <ul class="dropdown-menu">
      <li><%= link_to 'Add Light Wound', "/tick_tracks/#{tick_track.id}/incWound?amount=1", :method => :put %></li>
      <li><%= link_to 'Add Major Wound', "/tick_tracks/#{tick_track.id}/incWound?amount=3", :method => :put %></li>
      <li><%= link_to 'Add Severe Wound', "/tick_tracks/#{tick_track.id}/incWound?amount=9", :method => :put %></li>
      <li><%= link_to 'Add Critical Wound', "/tick_tracks/#{tick_track.id}/incWound?amount=27", :method => :put %></li>
      <li><%= link_to 'Reset All Wounds', "/tick_tracks/#{tick_track.id}/resetWound", :method => :put %></li>
      <li><%= link_to 'Kill Character', tick_track, method: :delete, data: { confirm: 'Are you sure you want to kill this character?' }%></li>
    </ul>
    </div>
  </p>
  </div>
<% end %>
</div>

<h2>Non-Player Characters</h2>

<div class="row well">
<% @NPCtracks = @tick_tracks.select { |obj| (obj.isPC == false && obj.campaign.active == true) } %>
<% @NPCtracks.sort!{ |a,b| a.name <=> b.name} %>
<% @NPCtracks.each do |tick_track| %>
  <div class="span2 trackbox <%= tick_track.tick != nil ? (tick_track.tick >=10 ? "offbalance" : "tick" + tick_track.tick.to_s()) : "emptytick" %> <%= tick_track.wound != nil ? (tick_track.wound == 0 ? "wound-none" : (tick_track.wound < 3 ? "wound-light" : (tick_track.wound < 9 ? "wound-major" : (tick_track.wound < 27 ? "wound-severe" : "wound-critical")))) : "errorwound" %>">
    <h4><%= link_to tick_track.name, edit_tick_track_path(tick_track) %><br></h4>
    <h1><%= tick_track.tick %><br></h1>
    <p><div class="btn-group">
      <%= link_to '1', "/tick_tracks/#{tick_track.id}/incTick?amount=1", :method => :put, :class => "btn btn-mini" %>
      <%= link_to '2', "/tick_tracks/#{tick_track.id}/incTick?amount=2", :method => :put, :class => "btn btn-mini" %>
      <%= link_to '3', "/tick_tracks/#{tick_track.id}/incTick?amount=3", :method => :put, :class => "btn btn-mini" %>
      <%= link_to '4', "/tick_tracks/#{tick_track.id}/incTick?amount=4", :method => :put, :class => "btn btn-mini" %>
      <%= link_to '5', "/tick_tracks/#{tick_track.id}/incTick?amount=5", :method => :put, :class => "btn btn-mini" %>
      <a class="btn dropdown-toggle btn-mini" data-toggle="dropdown" href="#"><i class="icon-fire icon-black"></i></a>
      <ul class="dropdown-menu">
      <li><%= link_to 'Add Light Wound', "/tick_tracks/#{tick_track.id}/incWound?amount=1", :method => :put %></li>
      <li><%= link_to 'Add Major Wound', "/tick_tracks/#{tick_track.id}/incWound?amount=3", :method => :put %></li>
      <li><%= link_to 'Add Severe Wound', "/tick_tracks/#{tick_track.id}/incWound?amount=9", :method => :put %></li>
      <li><%= link_to 'Add Critical Wound', "/tick_tracks/#{tick_track.id}/incWound?amount=27", :method => :put %></li>
      <li><%= link_to 'Reset All Wounds', "/tick_tracks/#{tick_track.id}/resetWound", :method => :put %></li>
      <li><%= link_to 'Kill Character', tick_track, method: :delete, data: { confirm: 'Are you sure you want to kill this character?' }%></li>
    </ul>
    </div>
  </p>
  </div>
<% end %>
</div>

<div class ="mainbuttons">
  <%= link_to 'Advance Tick', "/decAll", :method => :post, :class => "btn btn-primary btn-large" %>
  <%= link_to 'New Character', new_tick_track_path, :class => "btn btn-large" %>
</div>
<% else %>
<div class= "nocampaign">
  <%= image_tag "/assets/stopwatch-s.gif" %><br>
  <%= link_to 'Click Here to Select a Campaign', "/campaigns/", :class => "btn btn-large" %>
</div>
<% end %>

app/views/tick_tracks/new.html.erb
<h2>New Character</h2>

<%= render 'form' %>

app/views/tick_tracks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tick_track.name %>
</p>

<p>
  <b>Tick:</b>
  <%= @tick_track.tick %>
</p>

<p>
  <b>Wound:</b>
  <%= @tick_track.wound %>
</p>

<p>
  <b>Ispc:</b>
  <%= @tick_track.isPC %>
</p>


<%= link_to 'Edit', edit_tick_track_path(@tick_track) %> |
<%= link_to 'Back', tick_tracks_path %>